### ISSUE TITLE
no toolbar appears

### ISSUE THREAD

**Issue by jmls** [donShakespeare/tinymceBubbleBar#1]
I'm trying to get bubblebar to work in an angular4 app. if I don't include 

    external_plugins: {
        bubbleBar: "./vendor/bubble.js", // plugin location
    },

then the editor works fine, and the menubar and toolbar appear in the editor
When the bubblebar is included, the toolbar disappears, so I am guessing that bubble has kicked in. However, when text is double-clicked, nothing appears 

what am I missing ?

**Comment by donShakespeare** [comment]
Are you using bubblebar Version 1 or 2?
Is your TinyMCE inline or iframe mode?

**Comment by jmls** [comment]
sorry, it's the v2 version, must be iFrame as I can't get inline to work ;)

**Comment by donShakespeare** [comment]
Use v1 for Iframe. I have not tweaked v2 to work on Iframes properly
